new starter template, based on cherry picked commits from VVB work
IPG-Automotive-UK/remix-starter-template pull request #1
Opened 2022-09-14 16:07 UTC by jegasriskantha

## Summary: 

- new starter template based on VVB work 
- includes sidebar, auth and breadcrumbs

2022-09-15 09:09 UTC, mattcorner commented
It would be nicer if 404 was wrapped in Layout so that we can navigate through the app.

![image](https://user-images.githubusercontent.com/27866636/190364239-4667a53e-c7ee-4acb-b6b9-49ecb20fb1a9.png)

2022-09-15 09:10 UTC, mattcorner commented
On 404 my favicon reverts to remix
![image](https://user-images.githubusercontent.com/27866636/190364439-4f1de095-1067-4561-9e36-f73cc2972364.png)

2022-09-15 09:14 UTC, mattcorner commented
Documentation link goes nowhere. Should we seed with an empty docusaurus?

2022-09-15 09:16 UTC, mattcorner commented
Even though I am on the example page, I get old tab headers. I don't think we've configured it to set anything, at the very least it should be the app name from the package.json as a default.

![image](https://user-images.githubusercontent.com/27866636/190365541-a6e52f69-5363-4a14-b6a1-4f2e2f1a9f3c.png)

2022-09-15 09:24 UTC, mattcorner requested changes

2022-09-15 09:24 UTC, mattcorner commented on app/src/Layout.tsx
> +  console.log(matches);
Breadcrumbs are being console logged

```suggestion
```

2022-09-15 09:24 UTC, mattcorner commented on package.json
> +  "name": "virtual-vehicle-builder",
```suggestion
  "name": "remix-starter-ipguk",
```

2022-09-15 09:36 UTC, mattcorner commented
Tested using `npx create-remix@latest --template=file://localhost/Users/matthewcorner/Repos/remix-starter-template`.

Works well and deploys instantly.

2022-09-22 19:53 UTC, dmbarry86 commented
@evoinea you can refer to my latest commits as an example how to build for production and serve from Docker.

Note the requirement to distinguish between IAM front-end and IAM back-end as two separate environment variables. You & @mattcorner probably didn't consider this so far when running in dev mode. In production mode, the front end of our apps needs to iframe the front-end of IAM app which would be the address users would acces IAM e.g. localhost:5006. There are also some back-end calls in our apps to back-end of IAM and these require a different address for server to server.

2022-09-22 20:02 UTC, dmbarry86 commented
> Documentation link goes nowhere. We should seed with an empty docusaurus if this is our documentation tool of choice for web tools.

Agree with this. You should also include an example API resource route, api/demo etc which includes apidoc built and served a API Reference link in the sidebar.

2022-09-22 20:37 UTC, dmbarry86 commented
> You should also include an example API resource route, api/demo etc which includes apidoc built and served from a API Reference link in the sidebar.

I've done this. I'll leave one of you to do docusaurus example.

2022-09-22 20:38 UTC, dmbarry86 commented
I spotted this plugin for apidoc which lets you inject apidoc success response from a typescript interface. Could be useful. I haven't included it in my demo. https://github.com/bangbang93/apidoc-plugin-ts

2022-09-29 12:21 UTC, dmbarry86 commented
@chhack94 I've fixed the issue with doc not loading correct page when running in dev mode. I've changed the config so all of the doc is served from / rather than /help/docs as it was setup previously. The /help/docs routing should be done in the API back-end that actually serves the built doc, not in the doc config itself. I suspect this is just a carry over from the very first docusuraus project that was setup (probably NGD). We should adopt this same pattern in other apps going forward.

2022-09-29 12:25 UTC, chhack94 commented
> @chhack94 I've fixed the issue with doc not loading correct page when running in dev mode. I've changed the config so all of the doc is served from / rather than /help/docs as it was setup previously. The /help/docs routing should be done in the API back-end that actually serves the built doc, not in the doc config itself. I suspect this is just a carry over from the very first docusuraus project that was setup (probably NGD). We should adopt this same pattern in other apps going forward.

awesome, im gonna adapt this to the VVB repo too 👍

2022-10-05 11:11 UTC, mattcorner commented
Solved issue where documentation was never actually being built and served as part of app.

2022-10-05 11:11 UTC, mattcorner approved these changes

2022-10-05 11:11 UTC, merged